spring.application.name=tienda

# asignamos puerto si existe variable de entorno (render) y por defecto sino
server.port=${PORT:8081}

servidor.http=localhost

# --- perfiles ---
# se incluye local para entorno local, obvio duh
spring.profiles.include=local

##############################################################

# --- debugging ---
# Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

# Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformat=hh:mm

logging.level.web=DEBUG
#############################################################