# --- Base de datos en Aiven ---
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&requireSSL=true&verifyServerCertificate=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# para mantener estandar de InnoDB del sql inicial despelgado en aiven
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ajustes para compatibilidad maxima con servicios en la nube
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=900000

#############################################################


# --- Firebase Storage ---
# Esta informacion se utiliza para obtener acceso a su storage.
firebase.bucket.name=techshop-4b5a8.firebasestorage.app
firebase.storage.path=techshop-nicole
firebase.json.path=firebase
# no se usa por cambios en StorageConfig.java (ruta hardcoded), 
# pero se pone para evitar errores de compilacion
firebase.json.file=firebase-auth.json
#############################################################

# --- Mailing ---
# se reemplaza para que se pueda usar en render sin pagar, puesto 587 esta bloqueado
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${SPRING_MAIL_USERNAME}
#spring.mail.password=${SPRING_MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# --- Resend Mail Configuration ---
resend.api.key=${RESEND_API_KEY}
resend.sender.email=${RESEND_SENDER_EMAIL}
resend.sender.name=${RESEND_SENDER_NAME}

#############################################################

# --- debugging ---
# valores: none, update, validate, create-drop, viable 
spring.jpa.hibernate.ddl-auto=validate

# never = bajo ninguna circumstancia corre scripts dentro de /resources
# valores:  always, never
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true

# mostrar queries sql en output
spring.jpa.show-sql=false

# formato a sql para legibilidad
spring.jpa.properties.hibernate.format_sql=false

# optimizacion para produccion, evita cargar vistas en cada click
spring.thymeleaf.cache=true

# logging.level.org.springframework.security=DEBUG

#############################################################
