spring.application.name=tienda
server.port=8081

#Fecha y hora de logs 
loggin.pattern.dateformat=hh:mm

#Para eliminar mensajes invasivos de Spring 
spring.main.banner-mode=off

#En desarrollo el cache del servidor false, en producción true
spring.trymeleaf.cache=false

